# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_faceDetect(object):
    def setupUi(self, faceDetect):
        faceDetect.setObjectName("faceDetect")
        faceDetect.resize(429, 300)
        self.centralwidget = QtWidgets.QWidget(faceDetect)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 21))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(40, 40, 351, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 371, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(40, 110, 351, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 91, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 230, 351, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 160, 71, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 160, 71, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(110, 160, 71, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        faceDetect.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(faceDetect)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 429, 18))
        self.menubar.setObjectName("menubar")
        faceDetect.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(faceDetect)
        self.statusbar.setObjectName("statusbar")
        faceDetect.setStatusBar(self.statusbar)

        self.retranslateUi(faceDetect)
        QtCore.QMetaObject.connectSlotsByName(faceDetect)

    def retranslateUi(self, faceDetect):
        _translate = QtCore.QCoreApplication.translate
        faceDetect.setWindowTitle(_translate("faceDetect", "MainWindow"))
        self.label.setText(_translate("faceDetect", "Input option:"))
        self.comboBox.setItemText(0, _translate("faceDetect", "Select file to detect"))
        self.comboBox.setItemText(1, _translate("faceDetect", "Open camera and Photo manually"))
        self.comboBox.setItemText(2, _translate("faceDetect", "Open camera and Photo automatically"))
        self.label_2.setText(_translate("faceDetect", "Detect method option:"))
        self.comboBox_2.setItemText(0, _translate("faceDetect", "Baidu"))
        self.comboBox_2.setItemText(1, _translate("faceDetect", "JD"))
        self.comboBox_2.setItemText(2, _translate("faceDetect", "SNN"))
        self.label_3.setText(_translate("faceDetect", "Result:"))
        self.label_4.setText(_translate("faceDetect", "Result will show here"))
        self.pushButton.setText(_translate("faceDetect", "Run"))
        self.pushButton_2.setText(_translate("faceDetect", "End"))
        self.pushButton_3.setText(_translate("faceDetect", "Photo"))
